// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJC8CPy2JBWicYWdz6CzSVxOeaCUpTVAM',
    appId: '1:365038387806:web:1e3ff0735a3b3e51442acf',
    messagingSenderId: '365038387806',
    projectId: 'twitchclone-2094b',
    authDomain: 'twitchclone-2094b.firebaseapp.com',
    storageBucket: 'twitchclone-2094b.appspot.com',
    measurementId: 'G-XQE5LLWFNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnfQ8rkPRKCpQupk7WqY8ZWAxmVFUTzLU',
    appId: '1:365038387806:android:9cbbd59305d2ffcf442acf',
    messagingSenderId: '365038387806',
    projectId: 'twitchclone-2094b',
    storageBucket: 'twitchclone-2094b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNAAgnlL5vaiaKCA0a4N-1R3l6LTO25W0',
    appId: '1:365038387806:ios:0b83eff000f394c9442acf',
    messagingSenderId: '365038387806',
    projectId: 'twitchclone-2094b',
    storageBucket: 'twitchclone-2094b.appspot.com',
    iosClientId: '365038387806-rqn9e7525idqojgck4js9is02jq1jbq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.twithcClone',
  );
}
